### ISSUE TITLE
seed_cns failed

### ISSUE THREAD

**Issue by linshengnan2020** [Nextomics/NextDenovo#91] opened 2020-10-14 14:39 UTC
**the log**
[INFO]2020-10-14 22:15:51,533 start...
[INFO] 2020-10-14 22:15:51,533 logfile: pid68284.log.info
[WARNING] 2020-10-14 22:15:51,534 Re-write workdir
[INFO] 2020-10-14 22:15:51,534 options: 
[INFO] 2020-10-14 22:15:51,534 {'sort_threads': 8, 'nodelist': '', 'rewrite': 1, 'blocksize': '2g', 'job_prefix': 'nextDenovo', 'job_type': 'local', 'minimap2_options_map': '-x map-pb', 'cns_threads': 8, 'map_threads': 8, 'sort_mem': '50g', 'seed_cutoff': '11066', 'input_fofn': '/home/linshengnan/03_work/00_dianthus_work/01_qumai345_genome/03_genome_asm/01_next/input.fofn', 'read_cutoff': '1k', 'input_type': 'raw', 'sort_options': '-m 50g -t 8 -k 40', 'parallel_jobs': '4', 'cluster_options': '', 'sge_queue': '', 'ctg_graphdir': '/home/linshengnan/03_work/00_dianthus_work/01_qumai345_genome/03_genome_asm/01_next/01_rundir/03.ctg_graph', 'pa_correction': '4', 'workdir': '/home/linshengnan/03_work/00_dianthus_work/01_qumai345_genome/03_genome_asm/01_next/01_rundir', 'minimap2_threads': (8, 8), 'minimap2_options_raw': '-x ava-pb -t 8', 'minimap2_options_cns': '-x ava-pb -t 8 -k17 -w17', 'cns_aligndir': '/home/linshengnan/03_work/00_dianthus_work/01_qumai345_genome/03_genome_asm/01_next/01_rundir/02.cns_align', 'seed_cutfiles': '20', 'raw_aligndir': '/home/linshengnan/03_work/00_dianthus_work/01_qumai345_genome/03_genome_asm/01_next/01_rundir/01.raw_align', 'task': 'all', 'ctg_cns_options': ' -p 8', 'deltmp': 1, '_random_round_with_less_accuracy': 0, 'rerun': 3, 'correction_options': '-p 8 -max_lq_length 1000', 'nextgraph_options': '-a 1'}
[INFO] 2020-10-14 22:15:51,534 skip mkdir: /home/linshengnan/03_work/00_dianthus_work/01_qumai345_genome/03_genome_asm/01_next/01_rundir
[INFO] 2020-10-14 22:15:51,534 skip mkdir: /home/linshengnan/03_work/00_dianthus_work/01_qumai345_genome/03_genome_asm/01_next/01_rundir/01.raw_align
[INFO] 2020-10-14 22:15:51,534 skip mkdir: /home/linshengnan/03_work/00_dianthus_work/01_qumai345_genome/03_genome_asm/01_next/01_rundir/02.cns_align
[INFO] 2020-10-14 22:15:51,535 skip mkdir: /home/linshengnan/03_work/00_dianthus_work/01_qumai345_genome/03_genome_asm/01_next/01_rundir/03.ctg_graph
[INFO] 2020-10-14 22:15:51,566 analysis tasks done
[INFO] 2020-10-14 22:15:51,566 skip step: db_split
[INFO] 2020-10-14 22:15:51,570 analysis tasks done
[INFO] 2020-10-14 22:15:51,603 skip step: raw_align
[INFO] 2020-10-14 22:15:51,646 analysis tasks done
[INFO] 2020-10-14 22:15:51,649 skip step: sort_align
[INFO] 2020-10-14 22:15:51,653 analysis tasks done
[INFO] 2020-10-14 22:15:51,659 total jobs: 1
[INFO] 2020-10-14 22:15:51,660 Throw jobID:[68286] jobCmd:[/home/linshengnan/03_work/00_dianthus_work/01_qumai345_genome/03_genome_asm/01_next/01_rundir/02.cns_align/01.seed_cns.sh.work/seed_cns01/nextDenovo.sh] in the local_cycle.
[ERROR] 2020-10-14 22:16:55,620 seed_cns failed: please check the following logs:
[ERROR] 2020-10-14 22:16:55,620 /home/linshengnan/03_work/00_dianthus_work/01_qumai345_genome/03_genome_asm/01_next/01_rundir/02.cns_align/01.seed_cns.sh.work/seed_cns01/nextDenovo.sh.e

**run.cfg**
[General]
job_type = local
job_prefix = nextDenovo
task = all # 'all', 'correct', 'assemble'
rewrite = yes # yes/no
deltmp = yes
rerun = 3
parallel_jobs = 4
input_type = raw
input_fofn = input.fofn
workdir = 01_rundir

[correct_option]
read_cutoff = 1k
seed_cutoff = 11066
blocksize = 2g
pa_correction = 20
seed_cutfiles = 20
sort_options = -m 50g -t 8 -k 40
minimap2_options_raw = -x ava-pb -t 10
correction_options = -p 8

[assemble_option]
minimap2_options_cns = -x ava-pb -t 8 -k17 -w17
nextgraph_options = -a 1

**/home/linshengnan/03_work/00_dianthus_work/01_qumai345_genome/03_genome_asm/01_next/01_rundir/02.cns_align/01.seed_cns.sh.work/seed_cns01/nextDenovo.sh.e**

hostname
+ hostname
cd /home/linshengnan/03_work/00_dianthus_work/01_qumai345_genome/03_genome_asm/01_next/01_rundir/02.cns_align/01.seed_cns.sh.work/seed_cns01
+ cd /home/linshengnan/03_work/00_dianthus_work/01_qumai345_genome/03_genome_asm/01_next/01_rundir/02.cns_align/01.seed_cns.sh.work/seed_cns01
time /home/linshengnan/00_bin/python /home/linshengnan/01_software/NextDenovo/lib/nextcorrect.py -f /home/linshengnan/03_work/00_dianthus_work/01_qumai345_genome/03_genome_asm/01_next/01_rundir/02.cns_align//01.seed_cns.input.idxs -i /home/linshengnan/03_work/00_dianthus_work/01_qumai345_genome/03_genome_asm/01_next/01_rundir/01.raw_align/03.sort_align.sh.work/sort_align01/input.seed.001.sorted.ovl -p 8 -max_lq_length 1000 -o cns.fasta;
+ /home/linshengnan/00_bin/python /home/linshengnan/01_software/NextDenovo/lib/nextcorrect.py -f /home/linshengnan/03_work/00_dianthus_work/01_qumai345_genome/03_genome_asm/01_next/01_rundir/02.cns_align//01.seed_cns.input.idxs -i /home/linshengnan/03_work/00_dianthus_work/01_qumai345_genome/03_genome_asm/01_next/01_rundir/01.raw_align/03.sort_align.sh.work/sort_align01/input.seed.001.sorted.ovl -p 8 -max_lq_length 1000 -o cns.fasta
[INFO] 2020-10-14 22:15:51,873 Corrected step options:
[INFO] 2020-10-14 22:15:51,873 Namespace(blacklist='/home/linshengnan/03_work/00_dianthus_work/01_qumai345_genome/03_genome_asm/01_next/01_rundir/01.raw_align/03.sort_align.sh.work/sort_align01/input.seed.001.sorted.ovl.bl', dbuf=False, fast=False, idxs='/home/linshengnan/03_work/00_dianthus_work/01_qumai345_genome/03_genome_asm/01_next/01_rundir/02.cns_align//01.seed_cns.input.idxs', max_cov_aln=130, max_lq_length=1000, min_cov_base=4, min_cov_seed=10, min_error_corrected_ratio=0.8, min_len_aln=500, min_len_seed=10000, out='cns.fasta', ovl='/home/linshengnan/03_work/00_dianthus_work/01_qumai345_genome/03_genome_asm/01_next/01_rundir/01.raw_align/03.sort_align.sh.work/sort_align01/input.seed.001.sorted.ovl', process=8, split=False)
[WARNING] 2020-10-14 22:15:51,973 Skip 70717 seeds in blacklist.
[INFO] 2020-10-14 22:15:52,172 Start a cns worker in 68291 from parent 68290
[INFO] 2020-10-14 22:15:52,173 Start a cns worker in 68292 from parent 68290
[INFO] 2020-10-14 22:15:52,173 Start a cns worker in 68293 from parent 68290
[INFO] 2020-10-14 22:15:52,175 Start a cns worker in 68294 from parent 68290
[INFO] 2020-10-14 22:15:52,175 Start a cns worker in 68295 from parent 68290
[INFO] 2020-10-14 22:15:52,176 Start a cns worker in 68296 from parent 68290
[INFO] 2020-10-14 22:15:52,176 Start a cns worker in 68297 from parent 68290
[INFO] 2020-10-14 22:15:52,177 Start a cns worker in 68298 from parent 68290
/home/linshengnan/03_work/00_dianthus_work/01_qumai345_genome/03_genome_asm/01_next/01_rundir/02.cns_align/01.seed_cns.sh.work/seed_cns01/nextDenovo.sh: line 5: 68290 Segmentation fault      (core dumped) /home/linshengnan/00_bin/python /home/linshengnan/01_software/NextDenovo/lib/nextcorrect.py -f /home/linshengnan/03_work/00_dianthus_work/01_qumai345_genome/03_genome_asm/01_next/01_rundir/02.cns_align//01.seed_cns.input.idxs -i /home/linshengnan/03_work/00_dianthus_work/01_qumai345_genome/03_genome_asm/01_next/01_rundir/01.raw_align/03.sort_align.sh.work/sort_align01/input.seed.001.sorted.ovl -p 8 -max_lq_length 1000 -o cns.fasta

could you please give me some advises ?  Thank you very much !

**Comment by moold** [comment] 2020-10-15 05:36
Hi, have you tried to run this shell `/home/linshengnan/03_work/00_dianthus_work/01_qumai345_genome/03_genome_asm/01_next/01_rundir/02.cns_align/01.seed_cns.sh.work/seed_cns01/nextDenovo.sh` manually?  Whether it worked?

**Comment by linshengnan2020** [comment] 2020-10-16 02:32
I ran this script manually according to your suggestion, and the same error was reported。And I have two sets of data, the same parameter runs, one set of data works well , and the other sets of data reported this error。

**Comment by moold** [comment] 2020-10-16 03:02
There are two solutions:
1. If the size of `seed_cns01/cns.fasta` is similar with `cns.fasta` in other directories, just ignore this read, and run the following commands:
    ```
    cd /home/linshengnan/03_work/00_dianthus_work/01_qumai345_genome/03_genome_asm/01_next/01_rundir/02.cns_align/01.seed_cns.sh.work/seed_cns01/
    samtools faidx cns.fasta
    awk '{print $1"\t"$3"\t"$2}' cns.fasta.fai > cns.fasta.idx
    touch nextDenovo.sh.done
    ```
    and then rerun the main task.

2. This error is usually caused by the minimap2-nd task encountering insufficient memory, so you need to rerun the minimap2-nd task related to this task `seed_cns01/nextDenovo.sh`.  

    The value of `-i` option in seed_cns01/nextDenovo.sh is the finally minimap2-nd task result related to this task. So, run `cd /home/linshengnan/03_work/00_dianthus_work/01_qumai345_genome/03_genome_asm/01_next/01_rundir/01.raw_align/03.sort_align.sh.work/sort_align01`, and then you will find a file named `input.fofn`, which listes all the minimap2-nd task results `input.seed.*.ovl` related to this task. Therefore, you need re-generated these files, and then re-run `sort_align01/nextDenovo.sh` and `seed_cns01/nextDenovo.sh`.

    To  regenerate these files `input.seed.*.ovl`, just `cd` to its directory and run `nextDenovo.sh`.

**Comment by linshengnan2020** [comment] 2020-10-20 07:18
I check my seed_cns01/cns.fasta , this is empty file . So I tried the second solution, it can works well until today met an error: ctg_graph failed.

**Comment by moold** [comment] 2020-10-20 13:27
Have tried to run ctg_graph manually? BTW, pls paste the full log to here.

**Comment by linshengnan2020** [comment] 2020-10-21 07:07
**the log**
hostname
+ hostname
cd /home/linshengnan/03_work/00_dianthus_work/01_qumai345_genome/03_genome_asm/01_next/01_rundir/03.ctg_graph/01.ctg_graph.sh.work/ctg_graph0
+ cd /home/linshengnan/03_work/00_dianthus_work/01_qumai345_genome/03_genome_asm/01_next/01_rundir/03.ctg_graph/01.ctg_graph.sh.work/ctg_graph0
time /home/linshengnan/01_software/NextDenovo/bin/nextgraph -a 1 -f /home/linshengnan/03_work/00_dianthus_work/01_qumai345_genome/03_genome_asm/01_next/01_rundir/03.ctg_graph/01.ctg_graph.input.seqs /home/linshengnan/03_work/00_dianthus_work/01_qumai345_genome/03_genome_asm/01_next/01_rundir/03.ctg_graph/01.ctg_graph.input.ovls -o nd.asm.p.fasta;
+ /home/linshengnan/01_software/NextDenovo/bin/nextgraph -a 1 -f /home/linshengnan/03_work/00_dianthus_work/01_qumai345_genome/03_genome_asm/01_next/01_rundir/03.ctg_graph/01.ctg_graph.input.seqs /home/linshengnan/03_work/00_dianthus_work/01_qumai345_genome/03_genome_asm/01_next/01_rundir/03.ctg_graph/01.ctg_graph.input.ovls -o nd.asm.p.fasta
[INFO] 2020-10-21 03:19:03 Initialize graph and reading...
[ERROR] failed to find ovl file type or empty file

**the solution**
cd  /home/linshengnan/03_work/00_dianthus_work/01_qumai345_genome/03_genome_asm/01_next/01_rundir/03.ctg_graph, and then I  find a file named 01.ctg_graph.input.ovls, which listes all the results /cns_align*/cns.filt.dovt.ovl. I checked every cns.filt.dovt.ovl in cns_align* directory，found some cns.filt.dovt.ovl is empty , and then re-run cns_align*/nextDenovo.sh to regenerate cns.filt.dovt.ovl. 
after regenerated the  cns.filt.dovt.ovl ,  cd /home/linshengnan/03_work/00_dianthus_work/01_qumai345_genome/03_genome_asm/01_next/01_rundir/03.ctg_graph/01.ctg_graph.sh.work/ctg_graph0 to re-run nextDenovo.sh .
after done above , then rerun the main task.

**Comment by linshengnan2020** [comment] 2020-10-21 07:10
hi, I have anthor question. I have run a 1G , diploid genome with 70~80% repetitive sequences genome . The coverage of my PacBio data is approximately 40 x. As a result the final assembly N50 is 157k . I would be interested how to adjust the parameters to improve the assembly result. Could you please give me some advises? Thank you very much!

**Comment by moold** [comment] 2020-10-21 13:10
Your seed length is too short, so you can try to increase `seed_cutoff` to see how about the result. BTW, it is better to sequence more longer reads.

**Comment by linshengnan2020** [comment] 2020-10-22 02:04
the seed length was generated by the seq_stat script. Is there any standard to  increase seed_cutoff ?

**Comment by moold** [comment] 2020-10-22 02:40
No, you should try it, such as set `-d 30`. The default option values are not suitable for all species with different sequencing depths. 
I will close this issue, if you still have problems unrelated to this topic, please open a new issue.

**Closed by moold** 2020-10-22 02:40 UTC

**Comment by linshengnan2020** [comment] 2020-10-22 07:26
thank you very much!
